<?php
namespace \InteractivePlus\PDK2020Core\Settings;
$USERNAME_MINLEN = 1;
$USERNAME_MAXLEN = 20;
$DISPLAYNAME_MINLEN = 1;
$DISPLAYNAME_MAXLEN = 15;
$SIGNATURE_MAXLEN = 40;
$PASSWORD_MINLEN = 5;
$PASSWORD_MAXLEN = 40;
$LOGIN_SINGLEIPMAXTRIAL_COUNT = 2;
$LOGIN_SINGLEIPMAXTRIAL_DURATION = 120; //2 mins
$AVATOR_MAX_SIZE = 200; //In kB
$PASSWORD_SALT = "";
$TOKEN_SALT = "";
$VERIFICATION_CODE_SALT = "";
$TOKEN_AVAILABLE_DURATION = 3600;
$VERIFICATION_CODE_AVAILABLE_DURATION = 300; //5 mins